### ISSUE TITLE
Add an example command to be run for illustration

### ISSUE THREAD

**Issue by Zaijo** [Kixunil/gocar#1]
Consider adding to README something like:

Given files ... (listing)
when you run `gocar whatever`
you get (new listing) and only changed files are recompiled.

**Comment by Kixunil** [comment]
Meh, this is huge WIP, so it isn't applicable. No arguments are parsed right now and paths are hard-coded.

I'll keep this open though, so I won't forget to add example once I have something working.

**Comment by Kixunil** [comment]
I manged to produce something a bit more useful, hence the example was added.

Feel free to reopen, if you still find it unclear.
